name: "Commit Verification"
description: "Verifies commit signatures for both repository commits and third-party dependencies"
branding:
  icon: "shield"
  color: "blue"

inputs:
  repository:
    description: "The full GitHub repository (e.g. owner/repo)"
    required: true
  branch:
    description: "The branch name"
    required: true
  token:
    description: "GitHub token"
    required: true
  commits-to-check:
    description: "Number of commits to check"
    required: true
  accept-expired-keys:
    description: "Treat expired but valid signatures as trusted"
    required: false
    default: "false"
  accept-untrusted-signers:
    description: "Treat signatures where email does not match as trusted"
    required: false
    default: "false"
  accept-uncertified-keys:
    description: "Treat valid signatures without certification as trusted"
    required: false
    default: "false"
  accept-missing-key:
    description: "Treat signatures with missing public keys as trusted"
    required: false
    default: "false"
  accept-github-automated:
    description: "Treat GitHub automated signatures as trusted"
    required: false
    default: "false"
  time-range:
    description: "Time-range duration for time-based checking (e.g. '4320h' for 180 days). Leave empty for commit-count based checking."
    required: false
    default: ""
  key-age-period:
    description: "Check PGP key age."
    required: false
    default: 730h


runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.commits-to-check }}
    - ${{ inputs.accept-expired-keys }}
    - ${{ inputs.accept-unauthorized }}
    - ${{ inputs.accept-uncertified-keys }}
    - ${{ inputs.accept-missing-key }}
    - ${{ inputs.accept-github-automated }}
    - ${{ inputs.time-period }}
    - ${{ inputs.key-age-period }}
